### ISSUE TITLE
Fabric Operations Console setup issue - No applicable identities in wallet

### ISSUE THREAD

**Issue by harikoduru** [hyperledger-labs/fabric-operations-console#308]
Following instructions to setup Console.

**Associate Identity**

- Switch to Nodes page and perform the following steps
- Select peer "org1_peer1 - local"
- Associate Identity
- Select "Org1MSP Admin"

I keep getting this message:  "There are no applicable identities in the wallet">

But I do have the Org1MSP Admin identity (that I am supposed to choose, per instructions) in the wallet.  What am I missing?
Please see attached screenshots.
Thanks in advance.
![wallet](https://user-images.githubusercontent.com/3150821/192190900-eb6e0791-e8bf-4719-b22f-f1872ba5e72f.png)
![org1-peer1-local](https://user-images.githubusercontent.com/3150821/192190917-429e8981-15f7-49e0-bfd1-1b5289797bad.png)

**Comment by dshuffma-ibm** [comment]
so that drop down gets populated by wallet identities that originate from a CA with with a matching root cert for the MSP of this peer. is it possible you have imported/created identities from a previous setup run? if so those will not match, even though the actual MSP ID is the same (the root certs will not match)

**Comment by harikoduru** [comment]
You were absolutely correct.  Cleaning up the volumes resolved the issue.
Thanks a bunch
