### ISSUE TITLE
Need information about APIs provided by fabric console

### ISSUE THREAD

**Issue by dshuffma-ibm** [hyperledger-labs/fabric-operations-console#80]
We need to add a section the to readme or faq about the apis provided by fabric console. 

The [swagger doc is here](https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml), but it needs some links to it so people can find it.

**Comment by nkaramolegos** [comment]
Thank you, so can I use this API to create new channels and deploy new smart contracts? Because I don't find such a resource. 
My idea is to use the operation console for:
1) first deploy the network
2) create new channels and update chaincode using the REST api
3) Invoke transactions using the fabric-sdk as show [here](https://github.com/hyperledger-labs/fabric-operations-console/blob/b9fb0da75aeb7deafde6ef64e8e635cc794ca1af/docs/using_console/console-create-app.md)

**Comment by dshuffma-ibm** [comment]
done
